name: chessaidev
dependencies:
    - python=2.7.12
    - nose
    - multipledispatch
    - cython
    - numpy
    - pip:
        - toolz==0.8.2
        - frozendict
        - python-chess
        - tqdm
        - python-chess
