/* This file is autogenerated, do not edit*/
#include "moc_blocks_graphics_view.cpp"
#include "moc_blocks_tree_widget.cpp"
#include "moc_descriptors_tree_widget.cpp"
#include "moc_easy_frame_rate_viewer.cpp"
#include "moc_easy_graphics_scrollbar.cpp"
#include "moc_easy_qtimer.cpp"
#include "moc_globals_qobjects.cpp"
#include "moc_main_window.cpp"
